// <auto-generated />
using System;
using EstacionamentoData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstacionamentoData.Migrations
{
    [DbContext(typeof(EstacionamentoContext))]
    [Migration("20191019211746_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("EstacionamentoDomain.Entities.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Chegada");

                    b.Property<TimeSpan?>("Duracao");

                    b.Property<string>("Placa")
                        .IsRequired();

                    b.Property<decimal?>("Preco");

                    b.Property<DateTime?>("Saida");

                    b.Property<int?>("TempoCobrado");

                    b.Property<decimal?>("ValorTotal");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("EstacionamentoDomain.Entities.Vigencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<decimal>("HoraAdicional");

                    b.Property<decimal>("ValorHora");

                    b.Property<DateTime>("VigenciaFim");

                    b.Property<DateTime>("VigenciaInicio");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Vigencias");
                });
#pragma warning restore 612, 618
        }
    }
}
